model_script : Charger_dummy.py
class_name: Charger_dummy
n_instances: 2
stateful: true #this tell the federate wheter or not activate the memory dict for the model todo dovrei pensare a un modo per far scegliere cosa memorizzare pere ora memorizza automaticamente tutto da implementare ancora
RL_training: false
inputs:
  - current
outputs:
  - voltage
params:
    'charge_rate': [1.8,7.2]
    'EV_lev': [1,2]
sim_params:
  'update_interval': [60,60]
  'start_ts': [0,0]
  'end_ts': [3600,3600]