fed_name: Charger
fed_conf:
  model_script : Charger_dummy.py
  class_name: Charger_dummy
  n_instances: 2
  stateful: true
  RL_training: true
  mem_attrs: []
fed_info:
  broker: null
  broker_init: null
  broker_key: null
  broker_port: null
  core_init: null #for debugging only
  core_name: charger_core
  core_type: zmq
  local_port: null
  separator: null
fed_flags:
  SLOW_RESPONDING: False
  DEBUGGING: False
  TERMINATE_ON_ERROR: True
  FORCE_LOGGING_FLUSH: False
  DUMPLOG: False
  OBSERVER: False
  UNINTERRUPTIBLE: False
  INTERRUPTIBLE: True
  SOURCE_ONLY: False
  ONLY_TRANSMIT_ON_CHANGE: False
  ONLY_UPDATE_ON_CHANGE: False
  WAIT_FOR_CURRENT_TIME_UPDATE: False
  RESTRICTIVE_TIME_POLICY: False
  ROLLBACK: False
  FORWARD_COMPUTE: False
  REALTIME: False
  SINGLE_THREAD_FEDERATE: False
  SINGLE_THREAD_CORE: False
  REENTRANT: False
  IGNORE_TIME_MISMATCH_WARNINGS: False
  USE_JSON_SERIALIZATION: False
  EVENT_TRIGGERED: False
  CALLBACK_FEDERATE : False
  AUTOMATED_TIME_REQUEST: False
fed_properties:
  TIME_DELTA: 1e-09
  TIME_PERIOD: 60
  TIME_OFFSET: 0.0
  TIME_RT_LAG: 0.0
  TIME_RT_LEAD: 0.0
  TIME_RT_TOLERANCE: 0.0
  TIME_INPUT_DELAY: 0.0
  TIME_OUTPUT_DELAY: 0.0
  TIME_STOPTIME: 3600.0
  TIME_GRANT_TIMEOUT: 0.0
  INT_CURRENT_ITERATION: 0
  INT_MAX_ITERATIONS: 50
  INT_LOG_LEVEL: 3
  INT_FILE_LOG_LEVEL: 3
  INT_CONSOLE_LOG_LEVEL: 3
  INT_LOG_BUFFER: 0
  INT_INDEX_GROUP: -972
fed_connections:
  sub: {}
  pub:
    0: [{
      "key": "Charger/0/voltage",
      "type": "double",
      "units": "V",
      "global": true
    }]
    1: [ {
      "key": "Charger/1/voltage",
      "type": "double",
      "units": "V",
      "global": true
    } ]
  end: {}
  inp:
    0: [ {
      "key": "0/current",
      "type": "double",
      "units": "A",
      "global": true,
      "targets": [
        "Battery/0/current",
      ]
    }]
    1: [ {
      "key": "1/current",
      "type": "double",
      "units": "A",
      "global": true,
      "targets": [
        "Battery/1/current",
      ]
    }]
model_conf:
  params:
    charge_rate: [ 1.8,7.2 ]
    EV_lev: [ 1,2 ]
    power: [0,0]
  inputs:
    current: [ 0.0, 0.0 ]
  outputs:
    voltage: [ 240, 120 ]
  messages: { } #todo could be removed
